---
title: "Downstream_Analysis"
author: "Jinny Chun"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library Loading

```{r}
library(Seurat)
library(STutility)
library(ggplot2)
library(patchwork)
library(dplyr)
library(Matrix)

```

## Load Data

Import the infotable including paths to the count matrix, coordinate metadata and images and create the object


```{r, sample1 (se1), CN73, warning=FALSE, results='hide'}
infoTable <- read.table("C:/Users/jinny/Rstudio/DP/info_table.csv", sep=";", header=T, stringsAsFactors = F)[c(1, 2), ]
infoTable$sample_id <- paste0("sample_", 1:nrow(infoTable))
```

```{r create_seurat}

se <- InputFromTable(infotable = infoTable)
```

```{r plot_features, fig.width=7, fig.height=7}
ST.FeaturePlot(se, features = c("nFeature_RNA"),indices = 1, pt.size = 2.5)
ST.FeaturePlot(se, features = c("nFeature_RNA"),indices = 2, pt.size = 2.5)
```


```{r qc_violin, fig.width=8, fig.height=4}

se$sample_id <- paste0("sample_", GetStaffli(se)@meta.data$sample)
se <- SetIdent(se, value = "day")
p <- VlnPlot(se, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2, pt.size = 0.5)
p

```


```{r loadimages}

se <- LoadImages(se, time.resolve = FALSE, xdim = 1e3)

```

```{r analysis_wf, eval=FALSE, include=TRUE}

se <- se %>% SCTransform(return.only.var.genes = FALSE, variable.features.n = NULL, variable.features.rv.th = 1.1)
```

```{r plot_images, fig.width=12, fig.height=6, out.width="100%"}

ImagePlot(se, method = "raster")

```

```{r}
head(VariableFeatures(se),10)
```

```{r dim.cluster}
se <- RunPCA(se, assay = "SCT", verbose = FALSE)
se <- FindNeighbors(se, reduction = "pca", dims = 1:30)
se <- FindClusters(se, verbose = FALSE)
se <- RunUMAP(se, reduction = "pca", dims = 1:30)
```

```{r}
se <- SetIdent(se, value = "seurat_clusters")

ST.FeaturePlot(se, features = "seurat_clusters", split.labels = F, indices = 1,pt.size = 4, custom.theme = theme(legend.title = element_blank(), plot.title = element_blank(), legend.position = "right"))

ST.FeaturePlot(se, features = "seurat_clusters", split.labels = F, indices = 2,pt.size = 4, custom.theme = theme(legend.title = element_blank(), plot.title = element_blank(), legend.position = "right"))

```

```{r}
DimPlot(se, pt.size = 1 , label = T)
```


```{r}
se.markers <- FindAllMarkers(se)  
head(se.markers)
inceasing <- se.markers %>% top_n(n = 100, wt = avg_log2FC)
```


```{r, heatmap CCA}

#top 20 genes
top20de <- se.markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC)
#top 10 genes
top10de <- se.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
#top 5 genes
top5de <- se.markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC)

top3de <- se.markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_log2FC)

top2de <- se.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC)

DoHeatmap(se, features = top2de$gene, size = 3, angle = 0)

```
